language: java


script: 
  - sudo apt update | echo y
  - sudo apt install nodejs | echo y
  - node --version
  - sudo apt-get update
  - sudo apt-get update
  - sudo apt-get install python-software-properties  
  - curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash –
  - sudo apt-get install nodejs | echo y
  - npm -v 
  - npm –version