language: java


script: 
  - sudo apt update | echo y
  - sudo apt install nodejs | echo y
  - node --version
  - sudo apt-get update
  - sudo apt-get update
  - sudo apt-get install python-software-properties  
  - curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash –
  - sudo apt-get install nodejs | echo y
  - npm -v 
  - npm –version
  # Fixear NODE js queda con version vieja
  - sudo apt-get install default-jdk | echo y
  - java -version
  - wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
  - unzip commandlinetools-linux-7583922_latest.zip
  - mv /home/travis/build/AlanGDC/mobileBot/cmdline-tools /home/travis/build/AlanGDC/mobileBot/tools
  - cd tools/
  - pwd
  - export PATH=/home/travis/build/AlanGDC/mobileBot/tools:/home/travis/build/AlanGDC/mobileBot/tools/bin:$PATH
  - sdkmanager 
#         /home/travis/build/AlanGDC/mobileBot/cmdline-tools