#   - sdkmanager --list
#   - sdkmanager --update
#   - sdkmanager --list
#   - echo "--install android image---"
#   - echo "y" | sdkmanager --install '$(EMULATOR_VERSION_28)'
#   - echo "--install HAXM---"
#   - echo "y" | sdkmanager --install 'extras;intel;Hardware_Accelerated_Execution_Manager'
# #5- Create avd device and start emulator
#   - echo "-----Create avd device-----"
#   - echo "no" | avdmanager create avd -n android_emulator -k '$(EMULATOR_VERSION_28)' -d 17 --force
#   - echo " "
#   - echo "-----Create avd device-----"
#   - echo " "
#   - echo "Emulator created successfully, launching it"
#   - echo " "
#   - echo "-----Create Emulator-----"
# # adb -e shell getprop init.svc.bootanim
#   - nohup emulator -avd android_emulator -gpu auto -no-window -camera-back none -camera-front none -memory 1536  -no-boot-anim -no-snapshot-save -accel on -engine qemu2 -no-audio > /dev/null 2>&1 &
# #  -verbose -no-window -no-audio
#   - echo "-----Create Emulator-----"
#   - adb devices
# #6- Reset adb
#   - adb kill-server && adb start-server
# #         /home/travis/build/AlanGDC/mobileBot/cmdline-tools


language: android
jdk: oraclejdk8
node_js:
  - '11.10.1'
env:
  global:
    - ANDROID_BUILD_TOOLS=28.0.3
  matrix:
    - API=19 ABI=armeabi-v7a  
cache:
  yarn: true
  directories:
    # Android SDK
    - $HOME/android-sdk-dl 
    - $HOME/android-sdk
    # Node modules
    - node_modules
    # Maven
    - $HOME/.m2
android:
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
  components:
    - android-$API
before_install:
  - sdkmanager --list
  - yes | sdkmanager "platforms;android-28"
  - PATH=$PATH:$JAVA_HOME/bin
  - curl -sL https://deb.nodesource.com/setup_14.x | sudo -E bash -
  # Install nodejs
  - sudo apt-get install nodejs
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH="$HOME/.yarn/bin:$PATH"
  - echo "y" | android update sdk -a --no-ui --filter sys-img-armeabi-v7a-android-$API
  - echo no | android create avd --force -n test -t android-$API --abi $ABI
  - emulator -avd test -no-skin -no-window &
  - android-wait-for-emulator
script:
  - adb shell input keyevent 82 &
  - wget https://ap-fileserver.veritran.com/abcl/qa.abcvisa.7.1.0.45948.apk
  - ls
  - pwd
  - cd appium
  - yarn
  - APK="/home/travis/build/AlanGDC/mobileBot/qa.abcvisa.7.1.0.45948.apk" ENV="./appium/test/features/prueba.feature" yarn test:android